"""add review model

Revision ID: 1c3f77b74fc3
Revises: 82d5e09f1d09
Create Date: 2026-05-04 00:19:20.995838

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c3f77b74fc3'
down_revision: Union[str, Sequence[str], None] = '82d5e09f1d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('review', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('review', sa.Column('shipment_id', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'review', ['shipment_id'])
    op.create_foreign_key(None, 'review', 'shipment', ['shipment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='unique')
    op.drop_column('review', 'shipment_id')
    op.drop_column('review', 'comment')
    op.drop_column('review', 'rating')
    op.drop_column('review', 'created_at')
    # ### end Alembic commands ###
