"""add client contact

Revision ID: 844519621c11
Revises: e2eb8ba66dd4
Create Date: 2026-05-02 00:43:17.226556

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844519621c11'
down_revision: Union[str, Sequence[str], None] = 'e2eb8ba66dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE shipment AS sh
        SET client_contact_email = s.email
        FROM seller AS s
        WHERE sh.seller_id = s.id
          AND sh.client_contact_email IS NULL
        """
    )
    op.execute(
        """
        UPDATE shipment
        SET client_contact_email = 'unknown@example.com'
        WHERE client_contact_email IS NULL
        """
    )
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('shipment_event_shipment_id_fkey'), 'shipment_event', type_='foreignkey')
    op.create_foreign_key(None, 'shipment_event', 'shipment', ['shipment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment_event', type_='foreignkey')
    op.create_foreign_key(op.f('shipment_event_shipment_id_fkey'), 'shipment_event', 'shipment', ['shipment_id'], ['id'])
    op.alter_column('shipment', 'client_contact_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
