"""partner field name changed

Revision ID: aec0608f3fbd
Revises: b6e2253428e9
Create Date: 2025-11-15 01:31:11.312220

"""
from typing import Sequence, Union
import sqlmodel


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec0608f3fbd'
down_revision: Union[str, Sequence[str], None] = 'b6e2253428e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('max_handling_capacity', sa.Integer(), nullable=False))
    op.drop_column('delivery_partner', 'max_handlingcapacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('max_handlingcapacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('delivery_partner', 'max_handling_capacity')
    # ### end Alembic commands ###
