"""change client_contact_phone type

Revision ID: 82d5e09f1d09
Revises: 9cf176155fa5
Create Date: 2026-05-03 01:13:16.739047

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d5e09f1d09'
down_revision: Union[str, Sequence[str], None] = '9cf176155fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'client_contact_phone',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(), # type: ignore
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment', 'client_contact_phone',
               existing_type=sqlmodel.sql.sqltypes.AutoString(), # type: ignore
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
