"""addt tag

Revision ID: b5883a213e0c
Revises: 1c3f77b74fc3
Create Date: 2026-05-04 22:23:11.551198

"""
from datetime import datetime
from typing import Sequence, Union
from uuid import uuid4

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.database.models import TagName

# revision identifiers, used by Alembic.
revision: str = 'b5883a213e0c'
down_revision: Union[str, Sequence[str], None] = '1c3f77b74fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('tag', sa.Column('name', sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATURE_CONTROLLED', 'GIFT', 'RETURN', 'DOCUMENTS', name='tagname'), nullable=False))
    op.add_column('tag', sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False)) # type: ignore
    tag_instructions = {
        TagName.EXPRESS: "Prioritize this shipment for the fastest available route.",
        TagName.STANDARD: "Handle with the default routing and normal delivery SLA.",
        TagName.FRAGILE: "Handle with extra care and avoid stacking or sudden impact.",
        TagName.HEAVY: "Use safe lifting equipment or team-lift when moving this shipment.",
        TagName.INTERNATIONAL: "Verify customs paperwork before cross-border handoff.",
        TagName.DOMESTIC: "Route within domestic lanes and local carrier network only.",
        TagName.TEMPERATURE_CONTROLLED: "Keep this shipment within its required temperature range.",
        TagName.GIFT: "Preserve gift packaging and avoid attaching pricing documents.",
        TagName.RETURN: "Follow reverse-logistics flow and verify return reason at intake.",
        TagName.DOCUMENTS: "Keep documents flat, dry, and free from folds or creases.",
    }

    for tag_name, instruction in tag_instructions.items():
        op.execute(
            sa.text(
                """
                INSERT INTO tag (id, created_at, name, instruction)
                VALUES (:id, :created_at, CAST(:name AS tagname), :instruction)
                """
            ).bindparams(
                id=uuid4(),
                created_at=datetime.utcnow(),
                name=tag_name.name,
                instruction=instruction,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'instruction')
    op.drop_column('tag', 'name')
    op.drop_column('tag', 'created_at')
    # ### end Alembic commands ###
